#!/bin/bash

cd `dirname $0`

basedir=`pwd`

function make_dot_link {
    ln -svf "$basedir/$1" "$HOME/.$1"
}

make_dot_link "bash_profile"
make_dot_link "gitconfig"
make_dot_link "hgrc"
make_dot_link "vimrc"
make_dot_link "vim"
make_dot_link "tmux.conf"

local_bin="$HOME/.local/bin"

function make_bin_link {
    dest="$local_bin/$1"
    ln -svf "$basedir/$1" $dest
    chmod a+x $dest
}

if ! [ -d $local_bin ]; then
    mkdir $local_bin
fi

make_bin_link "makegif"
