#!/bin/bash

if [ -z $3 ]; then
    echo "Usage: makegif SOURCE_FILE COLORS WIDTH DEST_FILE"
    exit 0
fi

ffmpeg -y -i $1 -vf palettegen=max_colors=$2 palette.png
ffmpeg -y -i $1 -i palette.png -filter_complex "scale=$3:-1:flags=lanczos[x];[x][1:v]paletteuse" $4

rm -f palette.png
