#!/bin/bash

cd `dirname $0`
base_dir=`pwd`

# Symbolic links to the dot files

function make_dot_link {
    dest="$HOME/.$1"
    [ -e $dest ] || ln -svf "$base_dir/$1" $dest
}

make_dot_link gitconfig

# bash

uname=`uname`

if [ "$uname" == "Linux" ]; then
    # Use .bash_aliases instead.
    [ -e ~/.bash_aliases ] || ln -svf "$base_dir/bashrc" ~/.bash_aliases
fi

# zsh

[ -e ~/.zshrc ] || ln -svf "$base_dir/zshrc" ~/.zshrc
[ -d ~/.config ] || mkdir ~/.config
[ -e ~/.config/starship.toml ] || ln -svf "$base_dir/starship.toml" ~/.config/starship.toml

# Symbolic links to the Windows user directories

if [ "$uname" == "Linux" ] && grep -i -q "microsoft" /proc/version; then
    username=`powershell.exe '$env:UserName' | sed -e 's/[^a-zA-Z0-9]*$//'`
    [ -e ~/Windows ] || ln -svf "/mnt/c/Users/$username" ~/Windows
fi
